package ru.sidnystorm.books.exception

class DuplicatedUserException: RuntimeException("user.exists")